apiVersion: v1
kind: Service
metadata:
  name: simple-backend
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: simple-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-backend
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: simple-backend
  template:
    metadata:
      labels:
        app: simple-backend
    spec:
      containers:
        - name: api
          image: public.ecr.aws/q7f3b2t9/simple-backend:latest
          imagePullPolicy: Always
          securityContext:
            readOnlyRootFilesystem: true
          ports:
            - containerPort: 8080
          env:
            - name: XRAY_ADDR
              value: "xray-service.amazon-cloudwatch:2000"